### PR TITLE
[FOLSPRINGB-60] : mod-spring-template: Liquibase configuration example

### PR DESCRIPTION
**Pull request by nirmalr-shah**
[FOLSPRINGB-60](https://issues.folio.org/browse/FOLSPRINGB-60)

## Purpose
1. Example on how to configure liquibase and generate log file. 
2. Provide the link to the Spring Data project documentation.

## Approach
Adding the required documentation in README.md file

### CODE REVIEW

**Review by arin-epm — APPROVED** [review]

**Review by arin-epm — APPROVED** [review]

**Review by TarasSpashchenko — DISMISSED** [review]
Only changes to the documentation are needed. Please remove all others. please check 
All you need here is just to explain how to configure the liquibase using the folio-spring-base. It could be done simply applying configuration like in one of the existing production modules. For example 

https://github.com/folio-org/mod-quick-marc/blob/master/src/main/resources/application.yaml#L25

**Comment by nirmalr-shah** [comment]
> Only changes to the documentation are needed. Please remove all others. please check All you need here is just to explain how to configure the liquibase using the folio-spring-base. It could be done simply applying configuration like in one of the existing production modules. For example
> 
> https://github.com/folio-org/mod-quick-marc/blob/master/src/main/resources/application.yaml#L25

Changes done as per this. Requesting your review!!!

**Review by arin-epm — APPROVED** [review]

**Comment by nirmalr-shah** [comment]
> Only changes to the documentation are needed. Please remove all others. please check All you need here is just to explain how to configure the liquibase using the folio-spring-base. It could be done simply applying configuration like in one of the existing production modules. For example
> 
> https://github.com/folio-org/mod-quick-marc/blob/master/src/main/resources/application.yaml#L25

Done

**Review by gurleenkaurbp — APPROVED** [review]

**Comment by nirmalr-shah** [comment]
> Only changes to the documentation are needed. Please remove all others. please check All you need here is just to explain how to configure the liquibase using the folio-spring-base. It could be done simply applying configuration like in one of the existing production modules. For example
> 
> https://github.com/folio-org/mod-quick-marc/blob/master/src/main/resources/application.yaml#L25

Already completed

**Comment by nirmalr-shah** [comment]
> Only changes to the documentation are needed. Please remove all others. please check All you need here is just to explain how to configure the liquibase using the folio-spring-base. It could be done simply applying configuration like in one of the existing production modules. For example
> 
> https://github.com/folio-org/mod-quick-marc/blob/master/src/main/resources/application.yaml#L25

Done

**Review by arin-epm — APPROVED** [review]

**Pull request merged**
